name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Create .env file to store API key
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "NEO4J_URI=${{ secrets.NEO4J_URI }}" >> .env
          echo "NEO4J_USERNAME=${{ secrets.NEO4J_USERNAME }}" >> .env
          echo "NEO4J_PASSWORD=${{ secrets.NEO4J_PASSWORD }}" >> .env
          echo "TAVILY_API_KEY=${{ secrets.TAVILY_API_KEY }}" >> .env


      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://nqtruong:$HF_TOKEN@huggingface.co/spaces/nqtruong/Job_Knowledge_Graph main